# Generated by Django 5.2.3 on 2025-06-16 09:28

import users.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=users.storages.PublicMediaStorage(),
                upload_to="profile_pics/",
            ),
        ),
    ]
