# Generated by Django 5.2.3 on 2025-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userskill_skill_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                max_length=15,
            ),
        ),
    ]
