# Generated by Django 5.2.3 on 2025-06-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
