# Generated by Django 5.2.3 on 2025-06-29 07:14

import django.db.models.deletion
import users.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("text_content", models.TextField()),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=users.storages.PublicMediaStorage(),
                        upload_to="journal_medias/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="users.userskill",
                    ),
                ),
            ],
        ),
    ]
