# Generated by Django 5.2.3 on 2025-07-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0001_initial"),
        ("users", "0002_remove_userskill_skill_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="youtube_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("user_skill", "title")},
        ),
    ]
