# Generated by Django 5.2.3 on 2025-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0002_journal_youtube_url_alter_journal_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="ai_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
