# Generated by Django 5.2.3 on 2025-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0003_journal_ai_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
