# Generated by Django 5.2.3 on 2025-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0004_journal_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="prompts",
            field=models.JSONField(default=list),
        ),
    ]
