# Generated by Django 5.2.3 on 2025-07-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0005_journal_prompts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journal",
            old_name="ai_summary",
            new_name="summary",
        ),
    ]
