# Generated by Django 5.2.3 on 2025-07-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0006_rename_ai_summary_journal_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="youtube_url",
        ),
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Article", "Article"),
                            ("Video", "Video"),
                            ("Book", "Book"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="journals.journal",
                    ),
                ),
            ],
        ),
    ]
