import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AmplifyWrapper from "./amplifyWrapper";
import NavMenu from "@/components/ui/navigation";
import { AuthContextProvider } from "@/context/auth";
import ClientProvider from "./clientProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider>
          <AuthContextProvider>
            <AmplifyWrapper />
            <NavMenu />
            {children}
            <Toaster
              position="bottom-center"
              visibleToasts={1}
              toastOptions={{ className: "!bg-white !text-red-500 !shadow-md" }}
            />
          </AuthContextProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
