# Generated by Django 5.2.3 on 2025-06-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[("Offered", "offered"), ("Wanted", "wanted")],
                        max_length=10,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[("pro", "Pro"), ("noob", "Noob")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
