# Generated by Django 5.2.3 on 2025-06-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("users", "0002_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="skill_type",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="user",
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[("Offered", "offered"), ("Wanted", "wanted")],
                        max_length=10,
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        blank=True,
                        choices=[("pro", "Pro"), ("noob", "Noob")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skill_entries",
                        to="skills.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "skill", "skill_type")},
            },
        ),
    ]
