# Generated by Django 5.2.3 on 2025-07-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_skill_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("name", "category")},
        ),
    ]
