# Generated by Django 5.2.3 on 2025-06-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_remove_skill_created_at_remove_skill_proficiency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userskill",
            old_name="updated_at",
            new_name="last_updated",
        ),
    ]
