# Generated by Django 5.2.3 on 2025-06-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_rename_updated_at_userskill_last_updated"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userskill",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="userskill",
            name="user",
        ),
    ]
