# Generated by Django 5.2.3 on 2025-06-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0003_alter_matchrequest_skills_offered_by_from_user_and_more"),
        ("skills", "0004_alter_userskill_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSkill",
        ),
    ]
