# Generated by Django 5.2.3 on 2025-06-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0002_remove_skill_created_at_remove_skill_proficiency_and_more"),
        ("users", "0002_alter_userprofile_profile_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="users.user",
                    ),
                ),
                (
                    "skills_offered_by_from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_matches",
                        to="skills.skill",
                    ),
                ),
                (
                    "skills_offered_by_to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="want_matches",
                        to="skills.skill",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "from_user",
                        "to_user",
                        "skills_offered_by_from_user",
                        "skills_offered_by_to_user",
                    )
                },
            },
        ),
    ]
