services:
  web:
    build:
      context: .
      args:
        ENV: production
    restart: always
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             gunicorn skillsswap.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - .env.prod

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
