name: UpSkillsr Backend CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{ secrets.AWS_INSTANCE_SG_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_EC2_REGION }}
      - name: Get Runner Ip Address
        id: ip
        uses: haythem/public-ip@v1.3
      - name: Whitelist Runner Ip Address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
      - name: Copy Backend Folder into EC2 Instance
        run: |
          rsync -avz --delete --exclude=.env* -e "ssh" ./backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }}:backend/
      - name: Restart Docker
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} \
          "cd backend/skillsswap && docker compose -f docker-compose.prod.yml up -d --build web"
      - name: Revoke Runner Ip Address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
          --protocol tcp \
          --port 22 \
          --cidr ${{ steps.ip.outputs.ipv4 }}/32
